### PR TITLE
Fix for Moodle 4.3

### PR DESCRIPTION
**Pull request by danielneis**
This fix some method calls that were deprecated on Moodle 4.3

### CODE REVIEW

**Comment by davosmith** [comment]
If you were to wrap those lines in `if (class_exists(\core_user\fields::class)) {` (and left the original function in the `} else {` clause, then the plugin could continue to be compatible with earlier Moodle versions (I know they're unsupported, but someone will probably still try it and complain).

**Comment by danielneis** [comment]
Those people do not need to update the plugin, they can stick to the older version

**Comment by davosmith** [comment]
In which case, I need to create a separate branch to hold the old version, so it can still be accessed, rather than adding a couple of lines of extra code to cover all bases?

As I'm not actively maintaining this plugin, I'm not going to start messing around with branches, but I will happily accept a patch that fixes compatibility with recent versions, without breaking it for older versions.

**Comment by TimeBandit001** [comment]
I created a patch that fixes compatibility with recent versions, without breaking it for older versions.

It's pull request #21

**Comment by davosmith** [comment]
Merged fix from @TimeBandit001 - this is no longer needed

**Pull request closed without merging**
